# Site settings
title: Pizza Theory 
email: ankitpanda1014@gmail.com

baseurl: "mathblog"
url: "http://sudoankit.github.io/mathblog/"
twitter_username: sudoankit
github_username:  sudoankit


future: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

